//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSWMS.NAVService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MSWMS.NAVService.INAVService")]
    public interface INAVService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/Ping", ReplyAction="http://tempuri.org/INAVService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetBarcode", ReplyAction="http://tempuri.org/INAVService/GetBarcodeResponse")]
        System.Threading.Tasks.Task<string> GetBarcodeAsync(string barcodeNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetHandheldScans", ReplyAction="http://tempuri.org/INAVService/GetHandheldScansResponse")]
        System.Threading.Tasks.Task<string> GetHandheldScansAsync(string actionType, string documentType, string documentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetHandheldScanQtyBaseScanned", ReplyAction="http://tempuri.org/INAVService/GetHandheldScanQtyBaseScannedResponse")]
        System.Threading.Tasks.Task<string> GetHandheldScanQtyBaseScannedAsync(string actionType, string documentType, string documentNo, string itemNo, string variantCode, string lotNo, string lotNoTo, string shippingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetLocations", ReplyAction="http://tempuri.org/INAVService/GetLocationsResponse")]
        System.Threading.Tasks.Task<string> GetLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetOnHandQuantities", ReplyAction="http://tempuri.org/INAVService/GetOnHandQuantitiesResponse")]
        System.Threading.Tasks.Task<string> GetOnHandQuantitiesAsync(string itemNo, string variantCode, string locationCode, string binCode, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetPriceDiscount", ReplyAction="http://tempuri.org/INAVService/GetPriceDiscountResponse")]
        System.Threading.Tasks.Task<string> GetPriceDiscountAsync(string itemNo, string variantCode, string unitOfMeasure);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetSetup", ReplyAction="http://tempuri.org/INAVService/GetSetupResponse")]
        System.Threading.Tasks.Task<string> GetSetupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/GetUsers", ReplyAction="http://tempuri.org/INAVService/GetUsersResponse")]
        System.Threading.Tasks.Task<string> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/IsBinCodeValid", ReplyAction="http://tempuri.org/INAVService/IsBinCodeValidResponse")]
        System.Threading.Tasks.Task<string> IsBinCodeValidAsync(string locationCode, string binCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/IsSerialNoUnique", ReplyAction="http://tempuri.org/INAVService/IsSerialNoUniqueResponse")]
        System.Threading.Tasks.Task<string> IsSerialNoUniqueAsync(string actionType, string documentType, string documentNo, string barcodeNo, string serialNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/ValidateUser", ReplyAction="http://tempuri.org/INAVService/ValidateUserResponse")]
        System.Threading.Tasks.Task<string> ValidateUserAsync(string domain, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/ValidateLotNo", ReplyAction="http://tempuri.org/INAVService/ValidateLotNoResponse")]
        System.Threading.Tasks.Task<string> ValidateLotNoAsync(string lotNoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/ItemReclassUpload", ReplyAction="http://tempuri.org/INAVService/ItemReclassUploadResponse")]
        System.Threading.Tasks.Task<string> ItemReclassUploadAsync(string documentNo, string barcodeNo, decimal quantity, string locationCode, string serialNo, string lotNo, string lotNoTo, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/MovementByBoxIsScanned", ReplyAction="http://tempuri.org/INAVService/MovementByBoxIsScannedResponse")]
        System.Threading.Tasks.Task<string> MovementByBoxIsScannedAsync(string locationCode, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/MovementByBoxValidate", ReplyAction="http://tempuri.org/INAVService/MovementByBoxValidateResponse")]
        System.Threading.Tasks.Task<string> MovementByBoxValidateAsync(string locationCode, string binCode, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/MovementByBoxUpload", ReplyAction="http://tempuri.org/INAVService/MovementByBoxUploadResponse")]
        System.Threading.Tasks.Task<string> MovementByBoxUploadAsync(string locationCode, string lotNo, string lotNoTo, string binCode, string binCodeTo, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/MovementByItemValidate", ReplyAction="http://tempuri.org/INAVService/MovementByItemValidateResponse")]
        System.Threading.Tasks.Task<string> MovementByItemValidateAsync(string locationCode, string barcodeNo, string binCode, string lotNo, string serialNo, decimal quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/MovementByItemUpload", ReplyAction="http://tempuri.org/INAVService/MovementByItemUploadResponse")]
        System.Threading.Tasks.Task<string> MovementByItemUploadAsync(string barcodeNo, decimal quantity, string locationCode, string serialNo, string lotNo, string lotNoTo, string binCode, string binCodeTo, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPickGetHeaders", ReplyAction="http://tempuri.org/INAVService/DirectedPickGetHeadersResponse")]
        System.Threading.Tasks.Task<string> DirectedPickGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPickGetLines", ReplyAction="http://tempuri.org/INAVService/DirectedPickGetLinesResponse")]
        System.Threading.Tasks.Task<string> DirectedPickGetLinesAsync(string documentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPickUpload", ReplyAction="http://tempuri.org/INAVService/DirectedPickUploadResponse")]
        System.Threading.Tasks.Task<string> DirectedPickUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string binCode, string shippingId, string destinationNo, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPutAwayGetHeaders", ReplyAction="http://tempuri.org/INAVService/DirectedPutAwayGetHeadersResponse")]
        System.Threading.Tasks.Task<string> DirectedPutAwayGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPutAwayGetLines", ReplyAction="http://tempuri.org/INAVService/DirectedPutAwayGetLinesResponse")]
        System.Threading.Tasks.Task<string> DirectedPutAwayGetLinesAsync(string documentNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/DirectedPutAwayUpload", ReplyAction="http://tempuri.org/INAVService/DirectedPutAwayUploadResponse")]
        System.Threading.Tasks.Task<string> DirectedPutAwayUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string binCode, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseReceiptGetHeaders", ReplyAction="http://tempuri.org/INAVService/WarehouseReceiptGetHeadersResponse")]
        System.Threading.Tasks.Task<string> WarehouseReceiptGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseReceiptGetQuantities", ReplyAction="http://tempuri.org/INAVService/WarehouseReceiptGetQuantitiesResponse")]
        System.Threading.Tasks.Task<string> WarehouseReceiptGetQuantitiesAsync(string documentNo, string receivingId, string rbid, string itemNo, string variantCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseReceiptGetQtyBase", ReplyAction="http://tempuri.org/INAVService/WarehouseReceiptGetQtyBaseResponse")]
        System.Threading.Tasks.Task<string> WarehouseReceiptGetQtyBaseAsync(string warehouseReceiptNo, string itemNo, string variantCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseReceiptUpload", ReplyAction="http://tempuri.org/INAVService/WarehouseReceiptUploadResponse")]
        System.Threading.Tasks.Task<string> WarehouseReceiptUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string rbId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WhseReceiptGetQtyBaseAlreadyScanned", ReplyAction="http://tempuri.org/INAVService/WhseReceiptGetQtyBaseAlreadyScannedResponse")]
        System.Threading.Tasks.Task<string> WhseReceiptGetQtyBaseAlreadyScannedAsync(string documentNo, string itemNo, string variantCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseShipmentGetHeaders", ReplyAction="http://tempuri.org/INAVService/WarehouseShipmentGetHeadersResponse")]
        System.Threading.Tasks.Task<string> WarehouseShipmentGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseShipmentUpload", ReplyAction="http://tempuri.org/INAVService/WarehouseShipmentUploadResponse")]
        System.Threading.Tasks.Task<string> WarehouseShipmentUploadAsync(string documentNo, string locationCode, string shippingId, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseShipmentIsScanned", ReplyAction="http://tempuri.org/INAVService/WarehouseShipmentIsScannedResponse")]
        System.Threading.Tasks.Task<string> WarehouseShipmentIsScannedAsync(string documentNo, string shippingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WarehouseShipmentIsValid", ReplyAction="http://tempuri.org/INAVService/WarehouseShipmentIsValidResponse")]
        System.Threading.Tasks.Task<string> WarehouseShipmentIsValidAsync(string documentNo, string shippingId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WhseShptCrossDockGetHeaders", ReplyAction="http://tempuri.org/INAVService/WhseShptCrossDockGetHeadersResponse")]
        System.Threading.Tasks.Task<string> WhseShptCrossDockGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WhseShptCrossDockUpload", ReplyAction="http://tempuri.org/INAVService/WhseShptCrossDockUploadResponse")]
        System.Threading.Tasks.Task<string> WhseShptCrossDockUploadAsync(string documentNo, string locationCode, string lotNo, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/WhseShptCrossDockIsScanned", ReplyAction="http://tempuri.org/INAVService/WhseShptCrossDockIsScannedResponse")]
        System.Threading.Tasks.Task<string> WhseShptCrossDockIsScannedAsync(string documentNo, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/PutAwayGetHeaders", ReplyAction="http://tempuri.org/INAVService/PutAwayGetHeadersResponse")]
        System.Threading.Tasks.Task<string> PutAwayGetHeadersAsync(string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/PutAwayByBoxIsLotValid", ReplyAction="http://tempuri.org/INAVService/PutAwayByBoxIsLotValidResponse")]
        System.Threading.Tasks.Task<string> PutAwayByBoxIsLotValidAsync(string documentNo, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/PutAwayByBoxIsScanned", ReplyAction="http://tempuri.org/INAVService/PutAwayByBoxIsScannedResponse")]
        System.Threading.Tasks.Task<string> PutAwayByBoxIsScannedAsync(string documentNo, string binCode, string lotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INAVService/PutAwayByBoxUpload", ReplyAction="http://tempuri.org/INAVService/PutAwayByBoxUploadResponse")]
        System.Threading.Tasks.Task<string> PutAwayByBoxUploadAsync(string documentNo, string binCode, string lotNo, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface INAVServiceChannel : MSWMS.NAVService.INAVService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NAVServiceClient : System.ServiceModel.ClientBase<MSWMS.NAVService.INAVService>, MSWMS.NAVService.INAVService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NAVServiceClient() : 
                base(NAVServiceClient.GetDefaultBinding(), NAVServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INAVService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NAVServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NAVServiceClient.GetBindingForEndpoint(endpointConfiguration), NAVServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NAVServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NAVServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NAVServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NAVServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NAVServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetBarcodeAsync(string barcodeNo)
        {
            return base.Channel.GetBarcodeAsync(barcodeNo);
        }
        
        public System.Threading.Tasks.Task<string> GetHandheldScansAsync(string actionType, string documentType, string documentNo)
        {
            return base.Channel.GetHandheldScansAsync(actionType, documentType, documentNo);
        }
        
        public System.Threading.Tasks.Task<string> GetHandheldScanQtyBaseScannedAsync(string actionType, string documentType, string documentNo, string itemNo, string variantCode, string lotNo, string lotNoTo, string shippingId)
        {
            return base.Channel.GetHandheldScanQtyBaseScannedAsync(actionType, documentType, documentNo, itemNo, variantCode, lotNo, lotNoTo, shippingId);
        }
        
        public System.Threading.Tasks.Task<string> GetLocationsAsync()
        {
            return base.Channel.GetLocationsAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetOnHandQuantitiesAsync(string itemNo, string variantCode, string locationCode, string binCode, string lotNo)
        {
            return base.Channel.GetOnHandQuantitiesAsync(itemNo, variantCode, locationCode, binCode, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> GetPriceDiscountAsync(string itemNo, string variantCode, string unitOfMeasure)
        {
            return base.Channel.GetPriceDiscountAsync(itemNo, variantCode, unitOfMeasure);
        }
        
        public System.Threading.Tasks.Task<string> GetSetupAsync()
        {
            return base.Channel.GetSetupAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetUsersAsync()
        {
            return base.Channel.GetUsersAsync();
        }
        
        public System.Threading.Tasks.Task<string> IsBinCodeValidAsync(string locationCode, string binCode)
        {
            return base.Channel.IsBinCodeValidAsync(locationCode, binCode);
        }
        
        public System.Threading.Tasks.Task<string> IsSerialNoUniqueAsync(string actionType, string documentType, string documentNo, string barcodeNo, string serialNo)
        {
            return base.Channel.IsSerialNoUniqueAsync(actionType, documentType, documentNo, barcodeNo, serialNo);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUserAsync(string domain, string username, string password)
        {
            return base.Channel.ValidateUserAsync(domain, username, password);
        }
        
        public System.Threading.Tasks.Task<string> ValidateLotNoAsync(string lotNoCode)
        {
            return base.Channel.ValidateLotNoAsync(lotNoCode);
        }
        
        public System.Threading.Tasks.Task<string> ItemReclassUploadAsync(string documentNo, string barcodeNo, decimal quantity, string locationCode, string serialNo, string lotNo, string lotNoTo, string userId)
        {
            return base.Channel.ItemReclassUploadAsync(documentNo, barcodeNo, quantity, locationCode, serialNo, lotNo, lotNoTo, userId);
        }
        
        public System.Threading.Tasks.Task<string> MovementByBoxIsScannedAsync(string locationCode, string lotNo)
        {
            return base.Channel.MovementByBoxIsScannedAsync(locationCode, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> MovementByBoxValidateAsync(string locationCode, string binCode, string lotNo)
        {
            return base.Channel.MovementByBoxValidateAsync(locationCode, binCode, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> MovementByBoxUploadAsync(string locationCode, string lotNo, string lotNoTo, string binCode, string binCodeTo, string userId)
        {
            return base.Channel.MovementByBoxUploadAsync(locationCode, lotNo, lotNoTo, binCode, binCodeTo, userId);
        }
        
        public System.Threading.Tasks.Task<string> MovementByItemValidateAsync(string locationCode, string barcodeNo, string binCode, string lotNo, string serialNo, decimal quantity)
        {
            return base.Channel.MovementByItemValidateAsync(locationCode, barcodeNo, binCode, lotNo, serialNo, quantity);
        }
        
        public System.Threading.Tasks.Task<string> MovementByItemUploadAsync(string barcodeNo, decimal quantity, string locationCode, string serialNo, string lotNo, string lotNoTo, string binCode, string binCodeTo, string userId)
        {
            return base.Channel.MovementByItemUploadAsync(barcodeNo, quantity, locationCode, serialNo, lotNo, lotNoTo, binCode, binCodeTo, userId);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPickGetHeadersAsync(string locationCode)
        {
            return base.Channel.DirectedPickGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPickGetLinesAsync(string documentNo)
        {
            return base.Channel.DirectedPickGetLinesAsync(documentNo);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPickUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string binCode, string shippingId, string destinationNo, string userId)
        {
            return base.Channel.DirectedPickUploadAsync(documentNo, barcodeNo, quantity, serialNo, lotNo, binCode, shippingId, destinationNo, userId);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPutAwayGetHeadersAsync(string locationCode)
        {
            return base.Channel.DirectedPutAwayGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPutAwayGetLinesAsync(string documentNo)
        {
            return base.Channel.DirectedPutAwayGetLinesAsync(documentNo);
        }
        
        public System.Threading.Tasks.Task<string> DirectedPutAwayUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string binCode, string userId)
        {
            return base.Channel.DirectedPutAwayUploadAsync(documentNo, barcodeNo, quantity, serialNo, lotNo, binCode, userId);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseReceiptGetHeadersAsync(string locationCode)
        {
            return base.Channel.WarehouseReceiptGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseReceiptGetQuantitiesAsync(string documentNo, string receivingId, string rbid, string itemNo, string variantCode)
        {
            return base.Channel.WarehouseReceiptGetQuantitiesAsync(documentNo, receivingId, rbid, itemNo, variantCode);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseReceiptGetQtyBaseAsync(string warehouseReceiptNo, string itemNo, string variantCode)
        {
            return base.Channel.WarehouseReceiptGetQtyBaseAsync(warehouseReceiptNo, itemNo, variantCode);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseReceiptUploadAsync(string documentNo, string barcodeNo, decimal quantity, string serialNo, string lotNo, string rbId, string userId)
        {
            return base.Channel.WarehouseReceiptUploadAsync(documentNo, barcodeNo, quantity, serialNo, lotNo, rbId, userId);
        }
        
        public System.Threading.Tasks.Task<string> WhseReceiptGetQtyBaseAlreadyScannedAsync(string documentNo, string itemNo, string variantCode)
        {
            return base.Channel.WhseReceiptGetQtyBaseAlreadyScannedAsync(documentNo, itemNo, variantCode);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseShipmentGetHeadersAsync(string locationCode)
        {
            return base.Channel.WarehouseShipmentGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseShipmentUploadAsync(string documentNo, string locationCode, string shippingId, string userId)
        {
            return base.Channel.WarehouseShipmentUploadAsync(documentNo, locationCode, shippingId, userId);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseShipmentIsScannedAsync(string documentNo, string shippingId)
        {
            return base.Channel.WarehouseShipmentIsScannedAsync(documentNo, shippingId);
        }
        
        public System.Threading.Tasks.Task<string> WarehouseShipmentIsValidAsync(string documentNo, string shippingId)
        {
            return base.Channel.WarehouseShipmentIsValidAsync(documentNo, shippingId);
        }
        
        public System.Threading.Tasks.Task<string> WhseShptCrossDockGetHeadersAsync(string locationCode)
        {
            return base.Channel.WhseShptCrossDockGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> WhseShptCrossDockUploadAsync(string documentNo, string locationCode, string lotNo, string userId)
        {
            return base.Channel.WhseShptCrossDockUploadAsync(documentNo, locationCode, lotNo, userId);
        }
        
        public System.Threading.Tasks.Task<string> WhseShptCrossDockIsScannedAsync(string documentNo, string lotNo)
        {
            return base.Channel.WhseShptCrossDockIsScannedAsync(documentNo, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> PutAwayGetHeadersAsync(string locationCode)
        {
            return base.Channel.PutAwayGetHeadersAsync(locationCode);
        }
        
        public System.Threading.Tasks.Task<string> PutAwayByBoxIsLotValidAsync(string documentNo, string lotNo)
        {
            return base.Channel.PutAwayByBoxIsLotValidAsync(documentNo, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> PutAwayByBoxIsScannedAsync(string documentNo, string binCode, string lotNo)
        {
            return base.Channel.PutAwayByBoxIsScannedAsync(documentNo, binCode, lotNo);
        }
        
        public System.Threading.Tasks.Task<string> PutAwayByBoxUploadAsync(string documentNo, string binCode, string lotNo, string userId)
        {
            return base.Channel.PutAwayByBoxUploadAsync(documentNo, binCode, lotNo, userId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INAVService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INAVService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.51.10:92/NAVService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NAVServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INAVService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NAVServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INAVService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INAVService,
        }
    }
}
